spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- SENDGRID SMTP ---
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587

spring.mail.username=apikey
spring.mail.password=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

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true