spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Configuração de email (para recuperação de senha) ---
# Exemplo usando Gmail. Troque pelo email/senha de app que vocês forem usar.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=federadosapp@gmail.com
spring.mail.password=jwbxucniwnncssjb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
