spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- SENDGRID SMTP ---
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587

spring.mail.username=apikey
spring.mail.password=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

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true